### ISSUE TITLE
Check Team Project 2 Submission

### ISSUE THREAD

**Issue by alexlvz** [Itay-Hefetz/ScientistsCompetition#1]
Related Task
 Open group repository
 Meet up with the representatives of the science museum 
 Write README File specified for the team project
 Open User Manual page in wiki
 Open Product page in wiki
 Open Team page in wiki
 Open Inception page in wiki
 Collaborate repository with Eran and Reuven

**Comment by robi-y** [comment]
Excellent work, some comments:
- update the project description via repo. settings (it still say "A template repository with wiki for a team project at JCE's software engineering course")
- Readme: remove or comment out badges that still point to jce-il/template-project, deployment link should not take to existing system!
- Inception: risks are mostly very general
  - planning: it is almost never a good idea to start with login as an MVP
  - diagram: a use case diagram in not optimal for discussing software structure, better use deployment or even class diagrams

**Comment by alexlvz** [comment]
ד"ר ראובן שלום,
ראינו את ההערות שלכם לגבי המשימה הראשונה, ואנו חושבים שחלק מהדברים שנרשמו אינם מדוייקים.
1.	לגבי טבלת הסיכונים, הסיכונים שרשמנו מאוד רלוונטים לפרוייקט שלנו, אמנם הם כלליים במידה מסויימת, אבל צוותים אחרים שרשמו סיכונים כלליים לא פחות ואפילו את אותם הסיכונים קיבלו את כל הנקודות.
 
2.	לגבי תכנון הפיתוח, יכול להיות שזה לא נכון להתחיל ממערכת הכניסה ואנו שמחים לקבל הערות כאלו, אך לא ברור מדוע להוריד על זה נקודות. מדובר כאן על משהו שלא למדנו עד היום, ונשמח גם להבין מדוע זה לא נכון ואיך כן כדאי להתחיל. אנחנו חושבים עדיין שלמערכת המדוברת במקרה שלנו רצוי מאוד להתחיל בצורה זו

3.	לגבי הuse-case, רוב הצוותים השתמשו גם כן בתרשים מסוג זה ולא ירדו להם נקודות על כך. לא ברור מדוע דווקא לנו ירד ניקוד על שימוש בתרשים זה בטענה שאינו מתאים לעמוד.

     4	לגבי הreadme, לא הייתה הוראה בשום מקום להוריד את הדברים שהיו כתובים בתבנית, ולכן לא עשינו כך. כמובן שנדע להבא, אך גם כאן לא ברור מדוע להוריד לנו נקודות על כך.

נכון שלא מדובר בחלק משמעותי בציון הסופי בקורס, אבל אלו דברים קטנים שמצטברים ואנו שואפים למצויינות בצוות ורוצים גם להבין מה הן הבעיות. אנו נלמד כמובן להבא מההערות ומבקשים כיוון שמדובר במשימה הראשונה לתקן את הבעיות הקיימות ולקבל ציון חדש.
נשמח להתייחסותך לגבי הסעיפים הנ"ל.

תודה רבה,
צוות ScientistsCompetition

**Comment by alexlvz** [comment]
ד"ר ראובן שלום,
ראינו את ההערות שלכם לגבי המשימה הראשונה, ואנו חושבים שחלק מהדברים שנרשמו אינם מדוייקים.
1.	לגבי טבלת הסיכונים, הסיכונים שרשמנו מאוד רלוונטים לפרוייקט שלנו, אמנם הם כלליים במידה מסויימת, אבל צוותים אחרים שרשמו סיכונים כלליים לא פחות ואפילו את אותם הסיכונים קיבלו את כל הנקודות.
 
2.	לגבי תכנון הפיתוח, יכול להיות שזה לא נכון להתחיל ממערכת הכניסה ואנו שמחים לקבל הערות כאלו, אך לא ברור מדוע להוריד על זה נקודות. מדובר כאן על משהו שלא למדנו עד היום, ונשמח גם להבין מדוע זה לא נכון ואיך כן כדאי להתחיל. אנחנו חושבים עדיין שלמערכת המדוברת במקרה שלנו רצוי מאוד להתחיל בצורה זו

3.	לגבי הuse-case, רוב הצוותים השתמשו גם כן בתרשים מסוג זה ולא ירדו להם נקודות על כך. לא ברור מדוע דווקא לנו ירד ניקוד על שימוש בתרשים זה בטענה שאינו מתאים לעמוד.

4.	לגבי הreadme, לא הייתה הוראה בשום מקום להוריד את הדברים שהיו כתובים בתבנית, ולכן לא עשינו כך. כמובן שנדע להבא, אך גם כאן לא ברור מדוע להוריד לנו נקודות על כך.

נכון שלא מדובר בחלק משמעותי בציון הסופי בקורס, אבל אלו דברים קטנים שמצטברים ואנו שואפים למצויינות בצוות ורוצים גם להבין מה הן הבעיות. אנו נלמד כמובן להבא מההערות ומבקשים כיוון שמדובר במשימה הראשונה לתקן את הבעיות הקיימות ולקבל ציון חדש.
נשמח להתייחסותך לגבי הסעיפים הנ"ל.

תודה רבה,
צוות ScientistsCompetition

**Comment by alexlvz** [comment]
ד"ר ראובן שלום,
ראינו את ההערות שלכם לגבי המשימה הראשונה, ואנו חושבים שחלק מהדברים שנרשמו אינם מדוייקים.
1.	לגבי טבלת הסיכונים, הסיכונים שרשמנו מאוד רלוונטים לפרוייקט שלנו, אמנם הם כלליים במידה מסויימת, אבל צוותים אחרים שרשמו סיכונים כלליים לא פחות ואפילו את אותם הסיכונים קיבלו את כל הנקודות.
 
2.	לגבי תכנון הפיתוח, יכול להיות שזה לא נכון להתחיל ממערכת הכניסה ואנו שמחים לקבל הערות כאלו, אך לא ברור מדוע להוריד על זה נקודות. מדובר כאן על משהו שלא למדנו עד היום, ונשמח גם להבין מדוע זה לא נכון ואיך כן כדאי להתחיל. אנחנו חושבים עדיין שלמערכת המדוברת במקרה שלנו רצוי מאוד להתחיל בצורה זו

3.	לגבי הuse-case, רוב הצוותים השתמשו גם כן בתרשים מסוג זה ולא ירדו להם נקודות על כך. לא ברור מדוע דווקא לנו ירד ניקוד על שימוש בתרשים זה בטענה שאינו מתאים לעמוד.

4.	לגבי הreadme, לא הייתה הוראה בשום מקום להוריד את הדברים שהיו כתובים בתבנית, ולכן לא עשינו כך. כמובן שנדע להבא, אך גם כאן לא ברור מדוע להוריד לנו נקודות על כך.

נכון שלא מדובר בחלק משמעותי בציון הסופי בקורס, אבל אלו דברים קטנים שמצטברים ואנו שואפים למצויינות בצוות ורוצים גם להבין מה הן הבעיות. אנו נלמד כמובן להבא מההערות ומבקשים כיוון שמדובר במשימה הראשונה לתקן את הבעיות הקיימות ולקבל ציון חדש.
נשמח להתייחסותך לגבי הסעיפים הנ"ל.

תודה רבה,
צוות ScientistsCompetition

**Comment by robi-y** [comment]
שלום
כל נושא הניקוד לא רלוונטי לדיון כאן. אם אתם חושבים שטעינו תפנו אלי במייל או
בפגישה
